---
title: "`ropenbio` Specification and Design"
author: "Viktor Senderov"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ropenbio specification and design}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


## Mechanism to interface with a triple store

### Low-level access

```
# Create a "connection"
s = ServerAccessOptions(url, authentication, repository_id, ...)

# Get the protocal version
get_protocol_version(s)

# Submit a raw query via POST
POST_query("SELECT * #...", s)

# Submit a raw query via GET
GET_query("SELECT * #...", s) 

# Adds Seralized data to store
add_data("PREFIX owl: http://#... \n http://openbiodiv.net/sample_id a owl:Thing.", s)
```

### Function constructors to create custom queries
#### query_function_constructor
```
lookup_pquery = "SELECT *
         WHERE {
          ?id rdfs:label %label
          }"

openbiodiv_lookup_id = query_function_constructor(s, lookup_pquery, prefix_list)

openbiodiv_lookup_id(label = "Teodor Georgiev") 
```

Here `openbiodiv_lookup_id` will execute the query 

```
"SELECT *
 WHERE {
       ?id rdfs:label "Teodor Georgiev"
}
```

#### add_statements_function_constructor(server_access_options, prefix_list)
#### clear_context_function_constuctor(server_access_options, prefix_list)

## Mechanism to create and serialize RDF

#### RDF(triples_list)
constucts an RDF object

#### add_triples(rdf_obj, triples_list)
adds a list of triples to an existing RDF object

#### add_triplee(rdf_obj, triple)
adds a triple to an existing RDF object

#### triple(subject, predicate, object)
subject: an Identifier object
predicate: an Indetifier object
object: an Identifier or a Literal or an anonymous triple

#### anon_triple(predicate, object)

#### seralize(rdf_obj)
Creates a Turtle string

## Mechanism to create Identifiers

#### Identifier(label, sao)
basically a lookup function for that label

#### qname(id)
returns the QNAME, i.e. openbiodiv:something

#### uri(id, angle)
returns the full URI, i.e. "http://openbiodiv.net/something" or "<http://openbiodiv.net/something>" if angle is set

## Mechanism to create Literals

#### Literal(chars, type, lang)
constructor

#### squote(lit)
returns text to be used in a Turtle serialization such as \"Sample sentence\"@en

## Mechanism to process XML

#### find_atoms(xml_node, atom_locations)
returns a list of literals or identifiers at the atom_locations `

Example 
```
author_atoms = find_atoms(xml, list(atom = "/author"))
```

#### break_up_xml(xml_node, component_locations)
retunrn a list of XML nodes found at component_locations
side effect: issue XML id attributes to these components

#### get_or_set_id(node)
#### parent_id(node)
#### root_id(node)

## Mechanism to read and parse files

#### xml2rdf(filename, upper_level_extractor)

upper_level_extractor is a function that takes in a XML node and returns RDF

## Extractors and Objects for OpenBiodiv

Constructors for the various objects in the OpenBiodiv model
```
a = Author(author_atoms)
```

RDFizers for the various obejct
```
as.rdf(a)
```

Extractors
```
author_extractor(xml)
# returns RDF
```
